# --------------- devtools ---------------
spring.devtools.restart.exclude=static/fe/**
spring.devtools.livereload.enabled=true

# Poll interval in milliseconds:
spring.devtools.restart.poll-interval=50

# Quiet period in milliseconds:
spring.devtools.restart.quiet-period=10
# --------------- / ---------------
